# Generated by Django 5.2 on 2025-05-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_group_members_group_created_at_group_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
