# Generated by Django 5.2 on 2025-06-04 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_groupmembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='myapp.group'),
        ),
    ]
